### ISSUE TITLE
Coverage badge not updated

### ISSUE THREAD

**Issue by htssouza** [wdm0006/DummyRDD#22]
I still see coverage as "69%":
https://github.com/wdm0006/DummyRDD/

On coveralls it already says "78%":
https://coveralls.io/github/wdm0006/DummyRDD?branch=master

Any idea of what is happening?

**Comment by wdm0006** [comment]
I'd guess it's cached somewhere (by github or coveralls), and will just take a little while to get updated.  If it's not in the next hour or two I can look into it.

**Comment by wdm0006** [comment]
Do a hard refresh and it should show up.
